### ISSUE TITLE
[Mediator] Fee appears not to be updating

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#1]
As toasts are missing, it is also not easy to see what's happening.

A manual refresh after the graphql call indicates that the data for the mediator has not been written.
![Peek 2022-05-22 19-50](https://user-images.githubusercontent.com/5065940/169734372-c7ea96d3-09fe-4362-bdf0-527e36de7a78.gif)

Tested on Chromium (Version 101.0.4951.64 (Official Build) snap (64-bit)) with an activated mediator account.
Eternl wallet extension 1.7.2

**Comment by manonthemat** [comment]
The fee is indeed updating (checked in the database), but no visual feedback is provided yet.

**Comment by eselkin** [comment]
Resolved. minCompensation now updates the backend (as it was doing), but also the frontend and shows text to confirm your choices. It additionally prevents odd numbers from being submitted on both the front and backends.
