### ISSUE TITLE
Mediators signing up as parties

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#14]
It happened on too many occasions that mediators sign up as parties, when in fact they want to sign up as mediators.
Now mediators cannot simply sign up, because we vet them.

While our party sign up has a clear "seeking mediation" sub-heading, it's most likely not clear enough for people eager to sign-up.

I propose a simple text-link under the create account button for people seeking to offer their mediation services through our platform.

**Comment by dsleylian** [comment]
@manonthemat where would the link direct them to? 
signup?mediator=true  ?

**Comment by dsleylian** [comment]
@manonthemat  just to clarify, where would the link direct them to?
signup?mediator=true  ?

**Comment by manonthemat** [comment]
@dsleylian, I propose this text with url to the preboarding form:

If you are a professional mediator wanting to offer your services on mediators.ai, please [complete this survey.](https://forms.gle/zFLokCwXnxzED6iH6)
