### ISSUE TITLE
Mediation step 2 may exclude available mediation slots

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#18]
The time-filter on New Mediation Step 2 excludes time blocks such as 11 PM - 3 AM in the Party's selection of general available times. (That's the _bug_ part).

I also suspected that we could improve the wording here.
The current explanation for the element looks like this.

> What time of day would you like the mediation to take place? Consider what time zone the counter party is in.

...

I wonder if we should get rid of the time pre-selection altogether as people's availabilities may differ greatly depending on the weekday.

**Comment by dsleylian** [comment]
it may be a good idea to remove that part all together (Best time of Day on the top part of new mediation step 2) and show ALL of the times available on the selected days on the next step (new mediation step 3) 

as to the wording, maybe on the next page we can add something like "you are in X timezone, consider that other party's zone when making the time selection" ? in addition to the 'select multiple times' snippet that is already there?

**Comment by manonthemat** [comment]
> it may be a good idea to remove that part all together (Best time of Day on the top part of new mediation step 2) and show ALL of the times available on the selected days on the next step (new mediation step 3)

Yes, please!

As for the next page, I'd rather urge people to indicate all of their available times. :thinking:
