### ISSUE TITLE
Session cost availability issue

### ISSUE THREAD

**Issue by Lauchan21** [Loxe-Inc/mediators.ai-qa#2]
I have created a new mediation and choose a lower costs, the availability day shown were May 25th and 26th, clicked on "save & continue" button. The next screen didn't show the day and time i previously selected and had a full greyed out rectangle (see attached screenshot).
![Screenshot (2)](https://user-images.githubusercontent.com/91590874/169964893-a99acaeb-1f7d-43fa-a65d-9b098d7e0b15.png)

When click on "Save mediation request" I then had the error prompt at the top (as per screenshot).

Went back and left the costs as the one suggested originally and I could then see the day and time and save the mediation request properly.

I suppose the error was because the calendar with available mediator per day is not refreshing properly or quickly enough.

**Comment by eselkin** [comment]
We believe this is resolved. Can you test your scenario again to check @Lauchan21
