### ISSUE TITLE
Selecting times

### ISSUE THREAD

**Issue by azbee** [Loxe-Inc/mediators.ai-qa#22]
As a party, when I am selecting available times, I have to click again on what I have already selected to deselect to be able to make another choice. I think it would be better if when I am clicking on another time, the prior selected time gets deselected.

**Comment by dsleylian** [comment]
Just to clarify, is this as Party B when you are choosing one final time?

**Comment by azbee** [comment]
> Just to clarify, is this as Party B when you are choosing one final time?

I believe so.

**Comment by manonthemat** [comment]
> Just to clarify, is this as Party B when you are choosing one final time?

Yes, this was for Party B for the final selection.

**Comment by manonthemat** [comment]
The change is now live on https://dev.mediators.ai - the push to the production site will happen later today.
