### ISSUE TITLE
Fee Slider

### ISSUE THREAD

**Issue by azbee** [Loxe-Inc/mediators.ai-qa#23]
As an (invited) party, when I try to change the fee the schedule disappears. If I have the option from 200 to 250 and I use the slider to decrease the fee but the schedule disappears, why have that option?

**Comment by eselkin** [comment]
Should probably say, "No mediators found who are within the price range" something like this.

**Comment by azbee** [comment]
Well if other mediators will come up when I change the fee, I think that would work but if no mediators will come up would it be better to just have the set price for the (invited) party to see?

**Comment by manonthemat** [comment]
I agree in that the slider should have the minimum value set to the point where there's an availability.
