### ISSUE TITLE
Email for the other party didnt arrive

### ISSUE THREAD

**Issue by Lauchan21** [Loxe-Inc/mediators.ai-qa#3]
The case has been created but the 2nd parti has not received the notification email.

Currently stuck at: Waiting on other parties to determine fee

Does the 2nd party need to have an account at Mediators.ai as well in order to receive the email and determine fee?

**Comment by eselkin** [comment]
We think this is solved now. But will follow up after more testing.

**Comment by Lauchan21** [comment]
Noted, let me know if/when you want me to retry ;-)

**Comment by eselkin** [comment]
It's live. You can retry. But there was something that didn't seem quite right in the Frontend's response to the email sent out.

**Comment by Lauchan21** [comment]
I have tried to create 2 new cases but the emails to counterpart did not arrive (1 was Gmail address the other was my company email address). It was not in the SPAM box either.

**Comment by eselkin** [comment]
It should be resolved now. There were two places handling emails and we consolidated into one.

**Comment by Lauchan21** [comment]
Tried to check if it was resolved but when creating a new case I cannot find no available available mediator (even when changing session cost and best time of day). So I will try in a few days again.

**Comment by Lauchan21** [comment]
I confirm counter party received email :-)
