### ISSUE TITLE
Did not receive mediation cancellation email as a party

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#30]

**Comment by eselkin** [comment]
When Party B or A cancel Party A or B should receive notification that Mediation is cancelled.

**Comment by dsleylian** [comment]
Fixed an issue with how email addresses were given to sendgrid. cancellation emails are working now for parties and a scheduled mediator
Currently, the relationship with the mediator isn't removed but the case is set to isCancelled=true. 
Should the relationships be removed? this happens for both REQUEST_AVAILABLE_SLOT and SCHEDULED relationships?
Also I'm not sure the check for when to pay back the parties in case of PartyWithdraw is accurate, we should review that 

branch MA-30-email on BE
