### ISSUE TITLE
Fix routing

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#32]
When using any direct link (e.g. case detail link), brave responds with an error message "Sorry, that page is missing. Do you want to check if a saved version is available on the Wayback Machine?", which is an indication that the routing (on prod) is not working properly.

**Comment by eselkin** [comment]
Need to investigate
check on dev
if only AWS amplify, check if there's a setting to allow rewriting links to index.

**Comment by manonthemat** [comment]
We're back on GCP for FE prod. So we don't have to deal with that idiotic trailing slash.

@dsleylian @victorcorcino, let's write some proper automated tests for this though.
