### ISSUE TITLE
Session date issue: Proposed date in the past

### ISSUE THREAD

**Issue by Lauchan21** [Loxe-Inc/mediators.ai-qa#5]
We are May 25th 2022 but the agenda also proposed session in the past (May 23rd and 24th).

![Screenshot (4)](https://user-images.githubusercontent.com/91590874/170205775-5b67b7bb-62b1-4e15-a0b9-867aeb415ad1.png)

**Comment by manonthemat** [comment]
Thanks for reporting. This has been fixed with the most recent deployment.
