### ISSUE TITLE
Mediation Fee enhancements

### ISSUE THREAD

**Issue by manonthemat** [Loxe-Inc/mediators.ai-qa#7]
![fee](https://user-images.githubusercontent.com/5065940/173942232-f9de6498-e845-4629-9fe2-af13aa1f7ebc.png)

> 400 ADA is your base rate for a 4 hour session.

My understanding is that the input actually reflects the _gross_ rate set by the mediator and is the combined cost to the parties.
In the case of 400 ADA, the two parties split the cost equally and each would pay 200 ADA to the smart contract that disburses the funds upon mediation completion.

If these assumptions are true, I suggest to provide more information (with reactive values in line with the input - here 400 ADA):
- 90%: Mediator take-home pay (360 ADA)
- 9%: Loxe Inc. (36 ADA)
- 1%: ADR Token Holders (4 ADA)

_While it may be simpler to set and display a mediator's rate, the mediators I spoke to have resonated well with the transparency regarding use of funds which further can be verified on the blockchain._

While we want to move eventually to stable coins, we're stuck with ADA for a while. Combined with the fact that the majority of our mediators are fairly new to blockchain and cryptocurrencies we should probably also provide at a minimum a link to [coingecko's ADA price](https://www.coingecko.com/en/coins/cardano).

Beyond the MVP we may want to explore more sophisticated methods to assist mediators in setting their fee.

I also feel that these two sentences could be simplified.

> All availabilities selected by parties will have this rate until you change it. Already requested slots will have the old rate.

Can this be rewritten as follows?

> Assigned (open or scheduled) cases are unaffected from the fee change.

**Comment by eselkin** [comment]
@manonthemat Can you give feedback on this ticket's completedness. I believe they got all the features, but they had a new thought that is in the PR phase that I'd like you to consider.

**Comment by manonthemat** [comment]
It looks fine, but the introduction of the USD price does not address the volatility.

**Comment by eselkin** [comment]
Any suggestion on how to address the volatility? That's the volatility of ADA, right? Do you mean, like set a dollar price and have the ADA vary based on that price point?
