### ISSUE TITLE
Suggestion: Rearrange the position of the different meditations

### ISSUE THREAD

**Issue by Lauchan21** [Loxe-Inc/mediators.ai-qa#8]
Looking at the different created mediation cases, it might be easier (browse through) the different cases if the active ones and cancelled ones are separated from each other.

Would it for example be possible to have the cancelled ones moved back to the bottom (away from the active ones)? Alternatively we could have an option next to STATUS on order to rearrange the cases based on status?
![Mediators ai Dispute Resolution Marketplace - Brave 16_6_2022 2_09_57 pm](https://user-images.githubusercontent.com/91590874/174004673-84bdc08d-0b2b-4b8f-9961-05087cda986a.png)

**Comment by eselkin** [comment]
Separate section for New (only seen by mediators), Pending (only seen by parties) Scheduled
Separate section for Cancelled

**Comment by eselkin** [comment]
done

**Comment by Lauchan21** [comment]
Thanks, it looks very good now!
